### ISSUE TITLE
DingTalk webhook in emt4j repo

### ISSUE THREAD

**Issue by netomi** [adoptium/.eclipsefdn#13]
There is currently a webhook defined for the emt4j repo:

https://github.com/adoptium/.eclipsefdn/blob/main/otterdog/adoptium.jsonnet#L423

It is related to dingtalk. The problem is that the url contains the access token, and is thus visible to everyone.

If the webhook is still needed, it is probably better to use this action triggered by issues instead that allows to also specify a secret:

https://github.com/marketplace/actions/dingtalk-webhook

the url itself could be stored as repo secret so that it will not be visible in the jsonnet configuration.

@gdams @mbarbero

**Comment by netomi** [comment]
There is also some information how to trigger the dingtalk robot hook from python3:

https://tmasjc.rbind.io/2019-11-10-trigger-dingtalk-webhook/

**Comment by netomi** [comment]
This webhook url would otherwise not be visible using any sort of API by GitHub.

**Comment by gdams** [comment]
ping @sanhong as he's more familiar with the repo

**Comment by sanhong** [comment]
@D-D-H  pls. talk a look at it.

**Comment by D-D-H** [comment]
@netomi 
Hi, this ding-talk webhook is used to send a notification to our internal ding group when a new issue is created.
It's acceptable for us to remove it.

**Comment by netomi** [comment]
@D-D-H  did you take a look at the link I added above? It shows a way how to use trigger that webhook via python but also using a secret value. If we would also set a secret value for the webhook we could leave everything in place. Would it possible for you to check if you can enable such secret for the dingtalk integration?

**Comment by D-D-H** [comment]
@netomi 

> did you take a look at the link I added above? 
Yes. But I don't think we need this webhook for the time being, and I will use the method you suggest when necessary.
Thanks.

**Comment by netomi** [comment]
so its ok to remove this webhook for the time being?

**Comment by D-D-H** [comment]
Yes, please.

**Comment by netomi** [comment]
Webhook has been removed.
